// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using groupsapi;

namespace groupsapi.Migrations
{
    [DbContext(typeof(GroupsContext))]
    [Migration("20210908163447_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GroupsAPI.Models.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialisationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SubgroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TutorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.HasIndex("SubgroupId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GroupsAPI.Models.Specialisation", b =>
                {
                    b.Property<Guid>("SpecialisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecialisationId");

                    b.HasIndex("GroupId");

                    b.ToTable("Specialisations");
                });

            modelBuilder.Entity("GroupsAPI.Models.Subgroup", b =>
                {
                    b.Property<Guid>("SubgroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubgroupId");

                    b.ToTable("Subgroups");
                });

            modelBuilder.Entity("GroupsAPI.Models.Group", b =>
                {
                    b.HasOne("GroupsAPI.Models.Subgroup", null)
                        .WithMany("Groups")
                        .HasForeignKey("SubgroupId");
                });

            modelBuilder.Entity("GroupsAPI.Models.Specialisation", b =>
                {
                    b.HasOne("GroupsAPI.Models.Group", null)
                        .WithMany("Specialisations")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("GroupsAPI.Models.Group", b =>
                {
                    b.Navigation("Specialisations");
                });

            modelBuilder.Entity("GroupsAPI.Models.Subgroup", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
