// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using groupsapi;

namespace groupsapi.Migrations
{
    [DbContext(typeof(GroupsContext))]
    partial class GroupsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GroupsAPI.Models.Group", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialisationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SpecialisationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TutorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.HasIndex("SpecialisationId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GroupsAPI.Models.Specialisation", b =>
                {
                    b.Property<string>("SpecialisationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecialisationId");

                    b.ToTable("Specialisations");
                });

            modelBuilder.Entity("GroupsAPI.Models.Subgroup", b =>
                {
                    b.Property<string>("SubgroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubgroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("Subgroups");
                });

            modelBuilder.Entity("GroupsAPI.Models.Group", b =>
                {
                    b.HasOne("GroupsAPI.Models.Specialisation", "Specialisation")
                        .WithMany()
                        .HasForeignKey("SpecialisationId");

                    b.Navigation("Specialisation");
                });

            modelBuilder.Entity("GroupsAPI.Models.Subgroup", b =>
                {
                    b.HasOne("GroupsAPI.Models.Group", "Group")
                        .WithMany("Subgroups")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GroupsAPI.Models.Group", b =>
                {
                    b.Navigation("Subgroups");
                });
#pragma warning restore 612, 618
        }
    }
}
