// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using teachingapi;

namespace teachingapi.Migrations
{
    [DbContext(typeof(TeachingContext))]
    partial class TeachingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ActivitiesAPI.Models.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ActivityId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("GroupsAPI.Models.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialisationId")
                        .HasColumnType("int");

                    b.Property<Guid?>("SpecialisationId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SpecialisationId1");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("GroupsAPI.Models.Specialisation", b =>
                {
                    b.Property<Guid>("SpecialisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecialisationId");

                    b.ToTable("Specialisation");
                });

            modelBuilder.Entity("GroupsAPI.Models.Subgroup", b =>
                {
                    b.Property<Guid>("SubgroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubgroupId");

                    b.HasIndex("ClassId");

                    b.HasIndex("GroupId");

                    b.ToTable("Subgroup");
                });

            modelBuilder.Entity("TeachingAPI.Models.Class", b =>
                {
                    b.Property<Guid>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassId");

                    b.HasIndex("ActivityId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("TeachingAPI.Models.ClassLesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassLessons");
                });

            modelBuilder.Entity("GroupsAPI.Models.Group", b =>
                {
                    b.HasOne("TeachingAPI.Models.Class", null)
                        .WithMany("Groups")
                        .HasForeignKey("ClassId");

                    b.HasOne("GroupsAPI.Models.Specialisation", "Specialisation")
                        .WithMany()
                        .HasForeignKey("SpecialisationId1");

                    b.Navigation("Specialisation");
                });

            modelBuilder.Entity("GroupsAPI.Models.Subgroup", b =>
                {
                    b.HasOne("TeachingAPI.Models.Class", null)
                        .WithMany("Subgroups")
                        .HasForeignKey("ClassId");

                    b.HasOne("GroupsAPI.Models.Group", "Group")
                        .WithMany("Subgroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TeachingAPI.Models.Class", b =>
                {
                    b.HasOne("ActivitiesAPI.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("TeachingAPI.Models.ClassLesson", b =>
                {
                    b.HasOne("TeachingAPI.Models.Class", "Class")
                        .WithMany("ClassLessons")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("GroupsAPI.Models.Group", b =>
                {
                    b.Navigation("Subgroups");
                });

            modelBuilder.Entity("TeachingAPI.Models.Class", b =>
                {
                    b.Navigation("ClassLessons");

                    b.Navigation("Groups");

                    b.Navigation("Subgroups");
                });
#pragma warning restore 612, 618
        }
    }
}
